### ISSUE TITLE
Grub check might fail on CentOS7

### ISSUE THREAD

**Issue by jcsdatera** [Datera/ddct#1]
Grub check might fail on CentOS7 since we are always looking for GRUB_CMDLINE_LINUX_DEFAULT

[root@node1 ddct]# cat /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet elevator=noop"
GRUB_DISABLE_RECOVERY="true"

[root@node1 ddct]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

**Comment by mattsmithdatera** [comment]
Addressed by 3f808b2
